import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat();

export default [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.jsx"],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2021,
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    rules: {
      "react/no-unescaped-entities": "off",
      "@next/next/no-page-custom-font": "off",
      "@next/next/no-img-element": "off",
      "@next/next/no-head-element": "off",
      "@next/next/no-script-component-in-head": "off",
      "@next/next/no-sync-scripts": "off",
      "@next/next/no-before-interactive-script-outside-document": "off",
      "@next/next/no-document-import-in-page": "off",
      "@next/next/no-script-tag-for-ids": "off",
      "next/core-web-vitals": "off",
      "@typescript-eslint/no-unused-expressions": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-this-alias": "off",
      "import/no-anonymous-default-export": "off",
      "react/jsx-no-useless-fragment": "off",
      "react/jsx-no-constructed-context-values": "off",
      "react/jsx-no-bind": "off",
      "react/jsx-no-duplicate-props": "off",
      "react/jsx-no-target-blank": "off",
      "react/jsx-no-script-url": "off",
      "react/jsx-no-useless-fragment": "off",
      "react/no-unescaped-entities": "off",
      "react/no-unknown-property": "off",
      "react/no-children-prop": "off",
      "react/display-name": "off",
      "react/prop-types": "off",
      "react/react-in-jsx-scope": "off",
      "react/require-default-props": "off",
      "react/no-danger": "off",
      "react/no-find-dom-node": "off",
      "react/no-did-mount-set-state": "off",
      "react/no-did-update-set-state": "off",
      "react/no-render-return-value": "off",
      "react/no-string-refs": "off",
      "react/no-unescaped-entities": "off",
      "react/no-unused-prop-types": "off",
      "react/no-will-update-set-state": "off",
      "react/prefer-es6-class": "off",
      "react/prefer-stateless-function": "off",
      "react/sort-comp": "off",
      "react/style-prop-object": "off",
      "react/jsx-boolean-value": "off",
      "react/jsx-closing-bracket-location": "off",
      "react/jsx-curly-spacing": "off",
      "react/jsx-equals-spacing": "off",
      "react/jsx-filename-extension": "off",
      "react/jsx-first-prop-new-line": "off",
      "react/jsx-handler-names": "off",
      "react/jsx-indent": "off",
      "react/jsx-indent-props": "off",
      "react/jsx-key": "off",
      "react/jsx-max-props-per-line": "off",
      "react/jsx-no-comment-textnodes": "off",
      "react/jsx-no-literals": "off",
      "react/jsx-pascal-case": "off",
      "react/jsx-sort-props": "off",
      "react/jsx-space-before-closing": "off",
      "react/jsx-tag-spacing": "off",
      "react/jsx-wrap-multilines": "off",
    },
  },
];
